### ISSUE TITLE
Missing 'version' property in package.json

### ISSUE THREAD

**Issue by tohagan** [eHealthAfrica/couchdb-bootstrap#31]

**Comment by tthew** [comment]
This is because we use [semantic-release](semantic-release/semantic-release) to handle versioning.

Perhaps we should consider adding something to the package.json in order to better facilitate installing directly from github repos, e.g;

```
version: "0.0.0-semantically-released"
```

@jo what do you think?

**Comment by jo** [comment]
Yes, this was absolutely on my todo list.

**Comment by tohagan** [comment]
ok cool.  You learn a new trick *every* day.   Thanks for this one.
