### ISSUE TITLE
Watch option

### ISSUE THREAD

**Issue by jo** [eHealthAfrica/couchdb-bootstrap#7]
Have a watch option which pusheds everytime a file is changed, similar to [watchify](https://github.com/substack/watchify).

**Comment by jo** [comment]
[chokidar](https://github.com/paulmillr/chokidar),
> A neat wrapper around node.js fs.watch / fs.watchFile / fsevents.

is used in watchify under the hood.

**Comment by jo** [comment]
maybe only for couchdb-push

**Comment by jo** [comment]
\cc @janl

**Comment by janl** [comment]
nice!
