### ISSUE TITLE
Find a better name

### ISSUE THREAD

**Issue by jo** [eHealthAfrica/couchdb-bootstrap#9]
And also a shorter executable or a short alias.

**Comment by jo** [comment]
Maybe `couchdb-manager` with a `cdbm` executable?

**Comment by jo** [comment]
I think I go with couchdb-bootstrap with a `cdbb` executable. I love how it looks like **cddb** :)

**Comment by stevebest** [comment]
I was thinking about the guys who help you move stuff, like friges, color TVs - and *couches*, get it? https://youtu.be/wTP2RUD_cL0
